Repository kopilot2024/kopilot, pull requests merged in 2024-08, with the labels that each got.

#88 Fix(#87): 줄바꿈 기준으로 긴 문장 탐지
  views/javascript/longSentence/longSentence.js
Labels: bug

#93 Refactor(#89): 히스토리 UI 개선
  views/css/storagePopup.css
  views/javascript/storage/versionStorage.js
Labels: refactor

#100 Refactor(#99): 부분 수정 응답을 스트림으로 받아온다
  src/clova/clova.controller.ts
  src/clova/constants/clova-request-headers-details.ts
  src/clova/constants/index.ts
  src/clova/constants/partial-modification.ts
  src/clova/constants/stream-request-header.ts
  src/clova/feedback.service.ts
  src/clova/interceptors/stream-interceptor.ts
  src/clova/parsed-sentence.service.ts
  src/clova/partial-modification.service.ts
  src/clova/repetitive-word.service.ts
  src/clova/types/clova-chat-completions/index.ts
  src/clova/types/clova-chat-completions/response-body.type.ts
  src/clova/types/clova-chat-completions/stream-response-body.type.ts
  src/clova/types/clova-property.type.ts
  src/clova/types/index.ts
  src/clova/types/partial-modification/command.type.ts
  src/clova/types/stream-token.type.ts
  src/clova/utils/clova-event.parser.ts
  src/clova/utils/index.ts
  src/clova/utils/request-api.ts
  src/clova/utils/request-body.transformer.ts
  views/css/editorBox.css
  views/css/index.css
  views/css/outputPopup.css
  views/css/writingTool.css
  views/javascript/components/alertPopup.js
  views/javascript/components/baseInput.js
  views/javascript/components/editorBox.js
  views/javascript/components/spinner.js
  views/javascript/components/writingTool.js
  views/partials/writing-tool.hbs
Labels: refactor

#101 Fix(#87): 정규식 마지막 버려지는 문제 수정
  views/javascript/longSentence/longSentence.js
Labels: bug

#104 Feature(#103): PR 설정을 자동화한다
  .github/pr-labels.yml
  .github/workflows/configure-pr.yml
Labels: feature

#102 Refactor(#65): 배포 파이프라인을 작성한다
  .github/workflows/cd.yml
  .gitignore
  docker-compose.yml
  nginx/default.conf
Labels: refactor

#107 Feature(#106): 이슈를 자동으로 프로젝트에 등록한다
  .github/workflows/add-to-project.yml
Labels: feature

#109 Fix(#108): score가 A+ 등 A, B, C, D가 아닌 경우 처리
  views/javascript/components/feedbackPopup.js
Labels: bug

#113 Fix(#111, #112): 어미 자동 완성에서 발견한 오류를 수정한다
  views/javascript/autoComplete/autoCompletion.js
  views/javascript/autoComplete/inputTracker.js
  views/javascript/components/textarea.js
Labels: bug

#114 Fix(#110): AI에게 직접 명령 시 스트림이 섞여 들어온다
  views/javascript/components/basePopup.js
  views/javascript/components/editorBox.js
  views/javascript/utils/domManager.js
Labels: bug

#116 Fix(#115): 맞춤법 하이라이팅 오류 수정
  views/javascript/spell/spellCheck.js
Labels: bug

#120 Refactor(#118): 유의어 캐싱 및 모델 업그레이드
  .github/workflows/cd.yml
  .github/workflows/configure-pr.yml
  docker-compose.yml
  package.json
  src/app.module.ts
  src/clova/clova.controller.ts
  src/clova/clova.module.ts
  src/clova/clova.service.ts
  src/clova/constants/clova-request-body-details.ts
  src/clova/constants/partial-modification.ts
  src/clova/services/feedback.service.ts
  src/clova/services/parsed-sentence.service.ts
  src/clova/services/partial-modification.service.ts
  src/clova/services/repetitive-word.service.ts
  src/clova/types/clova-response.type.ts
  src/clova/types/partial-modification/cache-value.type.ts
  src/clova/types/partial-modification/index.ts
  src/clova/utils/request-body.transformer.ts
  src/clova/utils/response-body.transformer.ts
  src/common/cache/cache.manager.ts
  src/common/cache/redis/redis.manager.ts
  src/common/cache/redis/redis.module.ts
Labels: refactor

#123 Fix(#121): 빈 문자열이나 공백 문자 요청을 막는다
  views/css/index.css
  views/css/repetitiveWord.css
  views/index.hbs
  views/javascript/components/editorBox.js
  views/partials/components/popup.hbs
  views/partials/output-popup.hbs
Labels: fix

#127 Refactor(#126): 히스토리 피드백 UI 수정
  views/css/feedbackSlide.css
  views/css/index.css
  views/css/storagePopup.css
Labels: refactor

#129 Fix(#121, #128): 긴 문장 공백 관련 이슈들 해결
  views/javascript/longSentence/longSentence.js
Labels: bug

#134 Fix(#121): trim() 함수 호출 부분 수정
  src/clova/services/parsed-sentence.service.ts
Labels: bug

#141 Fix(#140): 반복되는 단어 수정 중 textarea 수정할 때 처리
  views/javascript/components/textarea.js
  views/javascript/index.js
  views/javascript/repetitiveWord/repetitiveWord.js
Labels: bug
